//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceClient.WcfServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WcfServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Hosgeldiniz", ReplyAction="http://tempuri.org/IService1/HosgeldinizResponse")]
        string Hosgeldiniz(string ad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Hosgeldiniz", ReplyAction="http://tempuri.org/IService1/HosgeldinizResponse")]
        System.Threading.Tasks.Task<string> HosgeldinizAsync(string ad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GeçersizKullanıcı", ReplyAction="http://tempuri.org/IService1/GeçersizKullanıcıResponse")]
        string GeçersizKullanıcı();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GeçersizKullanıcı", ReplyAction="http://tempuri.org/IService1/GeçersizKullanıcıResponse")]
        System.Threading.Tasks.Task<string> GeçersizKullanıcıAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/FavorilereEklendi", ReplyAction="http://tempuri.org/IService1/FavorilereEklendiResponse")]
        string FavorilereEklendi();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/FavorilereEklendi", ReplyAction="http://tempuri.org/IService1/FavorilereEklendiResponse")]
        System.Threading.Tasks.Task<string> FavorilereEklendiAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ekleme", ReplyAction="http://tempuri.org/IService1/eklemeResponse")]
        double ekleme(double n1, double n2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ekleme", ReplyAction="http://tempuri.org/IService1/eklemeResponse")]
        System.Threading.Tasks.Task<double> eklemeAsync(double n1, double n2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/silme", ReplyAction="http://tempuri.org/IService1/silmeResponse")]
        double silme(double n1, double n2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/silme", ReplyAction="http://tempuri.org/IService1/silmeResponse")]
        System.Threading.Tasks.Task<double> silmeAsync(double n1, double n2);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WcfServiceClient.WcfServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WcfServiceClient.WcfServiceReference1.IService1>, WcfServiceClient.WcfServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Hosgeldiniz(string ad) {
            return base.Channel.Hosgeldiniz(ad);
        }
        
        public System.Threading.Tasks.Task<string> HosgeldinizAsync(string ad) {
            return base.Channel.HosgeldinizAsync(ad);
        }
        
        public string GeçersizKullanıcı() {
            return base.Channel.GeçersizKullanıcı();
        }
        
        public System.Threading.Tasks.Task<string> GeçersizKullanıcıAsync() {
            return base.Channel.GeçersizKullanıcıAsync();
        }
        
        public string FavorilereEklendi() {
            return base.Channel.FavorilereEklendi();
        }
        
        public System.Threading.Tasks.Task<string> FavorilereEklendiAsync() {
            return base.Channel.FavorilereEklendiAsync();
        }
        
        public double ekleme(double n1, double n2) {
            return base.Channel.ekleme(n1, n2);
        }
        
        public System.Threading.Tasks.Task<double> eklemeAsync(double n1, double n2) {
            return base.Channel.eklemeAsync(n1, n2);
        }
        
        public double silme(double n1, double n2) {
            return base.Channel.silme(n1, n2);
        }
        
        public System.Threading.Tasks.Task<double> silmeAsync(double n1, double n2) {
            return base.Channel.silmeAsync(n1, n2);
        }
    }
}
